### ISSUE TITLE
can't launch asana gem

### ISSUE THREAD

**Issue by bricemaurin** [Asana/ruby-asana#69]
Hi there
I'm trying to use the asana gem to start a new project, but can't even launch it...do you know how to proceed ?

```
➜  ~ gem install asana
Successfully installed asana-0.8.1
1 gem installed
➜  ~ irb
irb(main):001:0> require 'asana'
Gem::LoadError: can't activate faraday-0.15.4, already activated faraday-0.12.2
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2289:in `check_version_conflict'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:86:in `block in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:85:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/asana-0.8.1/lib/asana/http_client.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:65:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/asana-0.8.1/lib/asana.rb:6:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:35:in `require'
	from (irb):1
	from /usr/local/var/rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

How to bypass the faraday error mentioned below ?

Thanks

**Comment by rossgrambo** [comment]
Hey @bricemaurin,

It looks like you already have an older version of faraday installed. You should be able to fix this by uninstalling faraday `gem uninstall faraday`. You might need to re-install asana after.

If you have other projects on your computer that rely on faraday 0.12.2, you might want to use [rbenv](https://github.com/rbenv/rbenv) or [rvm](https://github.com/rvm/rvm) to manage packages.

Let me know if there's any other issues.
